// Measurements from ErgoDox design.
SWITCH_PLATE_THICKNESS = 3;
SWITCH_HOLE_SIZE = 13.97;
SWITCH_NOTCH_WIDTH = 3.5001;
SWITCH_NOTCH_DEPTH = 0.8128;

SWITCH_CENTER_Y_SPACING = 19;
SWITCH_CENTER_X_SPACING = 19;

BOTTOM_CASE_MINIMUM_THICKNESS = 3;
BOTTOM_CASE_TENTING_ANGLE = 18;

THUMB_MATRIX_ROTATION = -12;
